### ISSUE TITLE
the dataset seem to be different 

### ISSUE THREAD

**Issue by CoMo6** [Aman-Verma-2307/Thoughtviz-Character-Recognition#1]

**Comment by CoMo6** [comment]
np.savez_compressed('./data/eeg/char/X_train_EBT_Thoughtviz.npz',np.array(X_train))
np.savez_compressed('./data/eeg/char/y_train_EBT_Thoughtviz.npz',np.array(y_train))
np.savez_compressed('./data/eeg/char/X_dev_EBT_Thoughtviz.npz',np.array(X_dev))
np.savez_compressed('./data/eeg/char/y_dev_EBT_Thoughtviz.npz',np.array(y_dev))

X_train = np.array(np.load('./X_train_EBT_HT_7525.npz',allow_pickle=True)['arr_0'],dtype=np.float16)
X_dev = np.array(np.load('./X_dev_EBT_HT_7525.npz',allow_pickle=True)['arr_0'],dtype=np.float16)
y_train = np.load('./y_train_EBT_HT_7525.npz',allow_pickle=True)['arr_0']
y_dev = np.load('./y_dev_EBT_HT_7525.npz',allow_pickle=True)['arr_0']
 
the char dataset from ThoughtViz  only has 14 channels but  you have 16 channels in  covariance_matrix function

**Comment by Aman-Verma-2307** [comment]
Hi @FlyingCan: There are 14 channels only the dataset, you can infer with the initial data-loading. For '16' channels discrepancy, you might be referring to the preprocessing codes present below. That code was written for an in-house curated dataset, you can alter it for 14 channels.
